name = "Adrenaserver Fork"
author = "Yiss"
version = "1.0.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00f0ce783c7e325432e308c1d9af3ffbcc265fc928371ff4659f58dfbfe74a47"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
