name = "Adrenaserver Fork"
author = "Yiss"
version = "1.0.0+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cbb7b2517d3bab81bfd93ba623fc945f20224ab638450e1957a9abe337c0bd01"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
