hash-format = "sha256"

[[files]]
file = "config/yosbr/config/ferritecore.mixin.properties"
hash = "1fbbea658d8af2a751857e70cf2d5930a24490cc4c24f8db9b49630a818b895c"

[[files]]
file = "config/yosbr/config/servercore/config.yml"
hash = "7ed78d3273aebb454ea062b841297b6a498364b997596383354402487e0e0434"

[[files]]
file = "config/yosbr/config/servercore/optimizations.yml"
hash = "c1347aa983b02f5e59fcbd4f931501e2705330c5cf25e723d3239b85e6b6e262"

[[files]]
file = "config/yosbr/config/vmp.properties"
hash = "ea15f808b99e85cffeceba875de0406012eb43b1780d366de3a4c82a9c9aece4"

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "01c5eb93a204f6b917b21aefd8e1c1268c8c0e63a9b6b34c4173bd7c8ff3dca5"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "54e3cc9a3c2a05cc879ffda7f4c97a89be0b648421d6c8fe92e2d3e5761abf20"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "e26dacab5ed497b7bf6500e389eba5e21cd4b9d7b38089045cd26818a4d2f589"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "a63765eb780a36cd968e2777d2c20bea5e5ca3ccdd920e64964e3746cf2a7f0d"
metafile = true

[[files]]
file = "mods/modernfix-mvus.pw.toml"
hash = "ceab5807172e236916b8386d352aca46895480867f607c5be07ff37da7fc9c85"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "18360f497689d81ce5b4a58571c099bf5a7f66e085ccd7196cd129158b328f15"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "0bdb14d12c298ab3a115ba719c6a6ee294bcfb97ed12efe53dd1ef753efc82d4"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "284e709de197c7bbd323489c83baf288006785e8cd8d3cf8b38cf7dbbbc36703"
metafile = true

[[files]]
file = "mods/tt20.pw.toml"
hash = "89010b27699fcd4c3596ec72b412bd12dc33eb5b1df79b96224cbad624929e45"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "989b6c4ff3dc08d7994667b4dfc9931a3b15876eabe4f9de7be8939153bb1fdc"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true
