name = "Adrenaserverfork"
author = "yiss"
version = "1.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ed6513fb07cbd06192fadbd9c7288b30eb6bac05e91a3ee2285ba784061f2e3"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
